---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zigbee2mqtt
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: zigbee2mqtt
      version: 9.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/koenkk/zigbee2mqtt
      tag: 1.26.0

    persistence:
      data:
        enabled: true
        type: pvc
        existingClaim: zigbee2mqtt-data

    env:
      ZIGBEE2MQTT_DATA: /data
      TZ: ${SETTING_TZ}

    # dummy values
    config:
      homeassistant: true
      device_options:
        retain: true
      permit_join: false
      mqtt:
        base_topic: zigbee2mqtt
        server: "mqtt://mqtt.home"
      serial:
        port: "tcp://192.168.1.90:6638"
      advanced:
        log_output:
          - console
        network_key: GENERATE
        pan_id: GENERATE
      frontend:
        port: 8080
