---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  chart:
    spec:
      # renovate: registryUrl=https://charts.longhorn.io
      chart: longhorn
      version: 1.2.3
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
  interval: 15m
  releaseName: longhorn
  values:
    # https://artifacthub.io/packages/helm/longhorn/longhorn?modal=values
    persistence:
      defaultClassReplicaCount: 2
      reclaimPolicy: Retain
      defaultClass: false
    defaultSettings:
      defaultReplicaCount: 2
      createDefaultDiskLabeledNodes: true
