---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: actions-runner-controller
  namespace: actions-runner-system
spec:
  interval: 5m
  chart:
    spec:
      chart: actions-runner-controller
      version: 0.20.0
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller-charts
        namespace: flux-system
  install:
    crds: CreateReplace
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 5

  values:
    env:
      TZ: ${SETTING_TZ}

    image:
      repository: summerwind/actions-runner-controller
      tag: v0.24.1

    podAnnotations:
      secret.reloader.stakater.com/reload: actions-runner-controller-auth

    authSecret:
      create: false
      name: actions-runner-controller-auth

    resources:
      requests:
        memory: 64Mi
      limits:
        memory: 128Mi

    metrics:
      serviceMonitor: true

    githubWebhookServer:
      enabled: false
