---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kured
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: kured
      version: 3.0.0
      sourceRef:
        kind: HelmRepository
        name: kured-charts
        namespace: flux-system
  values:
    updateStrategy: RollingUpdate
    configuration:
      timeZone: ${SETTING_TZ}
      startTime: "2:00"
      endTime: "5:00"
      notifyUrl: ${SECRET_DISCORD_WEBHOOK}
    metrics:
      create: true
    tolerations:
      # this toleration is to have kured runnable on tainted master nodes
      # remove it if your masters can't run pods
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
